import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar";

const lora = Lora({
  weight: "400",
  subsets: ["latin"],
  display: "block",
  style: "italic",
});

export const metadata: Metadata = {
  title: "WorkSkillHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.jpg" />
      </head>
      <body className={lora.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
